# Generated by Django 5.0.4 on 2024-07-14 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='productos',
        ),
        migrations.AddField(
            model_name='venta',
            name='total_usd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Producto_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('total_usd', models.IntegerField(default=0)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('Venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.venta')),
            ],
        ),
    ]
