# Generated by Django 5.0.4 on 2024-07-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_producto_venta_total_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto_venta',
            old_name='total',
            new_name='acumulado',
        ),
    ]
